### ISSUE TITLE
add OpenStreetMap layers?

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#1]
@juan-guerschman logged an issue in the TerriaJS repo that belongs here: TerriaJS/terriajs#1605

> Is it possible to add overlays from OpenStreetMap? I'm particularly interested in being able to overlay coastlines, borders, labels and roads, particularly useful if the user wants to show raster layers in 100% opacity.
> I'm thinking about something like this: http://go.nasa.gov/1ZwE10E

**Comment by meh9** [comment]
Those OSM layers are actually sourced from a NASA server where they have made those layers available. Depending on the license we may be able to just use their layers.

However, as you noted in your separate email some of these layers exist in NationalMap already, but many of them will be for Australia only.

We'll look into it.

**Comment by juan-guerschman** [comment]
Thanks, yes that's what I guessed. Best scenario find a WMS service we can already use. Worst case scenario, I think they can be downloaded from [http://planet.openstreetmap.org/](http://planet.openstreetmap.org/) and served from AusCover or similar. 

thanks

**Comment by juan-guerschman** [comment]
BTW, The Worldview is open source [https://github.com/nasa-gibs/worldview](https://github.com/nasa-gibs/worldview), they have a bunch of very cool stuff. Is it as simple as copying some of those features or I am too naive? For example the "Take a snapshot" thingy is cool.

**Comment by meh9** [comment]
Yeah, it looks good, in particular this line:

> We encourage interested developers to build their own clients or integrate NASA imagery into their existing ones using these services.

**Comment by meh9** [comment]
I've been having a look at those NASA layers, but there was a Terria bug blocking it that is now fixed in the next release:

https://github.com/TerriaJS/terriajs/issues/2327

This is the webservice to use:

https://gibs-a.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi

**Comment by juan-guerschman** [comment]
Great, does this mean that the wmts service will / cna be included in the next release of GEOGLAM RAPP Map?

**Comment by meh9** [comment]
Yep, I've just tested a prototype of it. Will let you know when we have something integrated properly.

Without borders:
<img width="1440" alt="screen shot 2017-01-20 at 11 46 29" src="https://cloud.githubusercontent.com/assets/5283003/22131343/ddd858d2-df06-11e6-8791-85a34e503693.png">


With borders:
<img width="1440" alt="screen shot 2017-01-20 at 11 46 47" src="https://cloud.githubusercontent.com/assets/5283003/22131352/f0b802c2-df06-11e6-8e5e-c0c87d3bf001.png">

**Comment by meh9** [comment]
I've added in a borders and a labels layer, they'll be in the next release.

**Comment by juan-guerschman** [comment]
hey @meh9 
some time in the past you did this. 
However, I was wondering how we could add roads. If you look in the example i sent  http://go.nasa.gov/1ZwE10E they offer three layers one being coastlines + borders + roads.

![image](https://user-images.githubusercontent.com/8801702/28817295-14478fec-76eb-11e7-8b8c-c28ee2f491d2.png)

In the web service we are grabbing the layers from there is no roads though https://gibs-a.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi but they would also be useful on top of our rasters. 
I've been trying to find where the roads are coming from in WorldView but no success. If you could find it I could try and add them to geoglam.json myself

**Comment by meh9** [comment]
@juan-guerschman the `Area Borders` layer we are using is the same one as you have a screenshot of above and does actually already include the roads. I hadn't even realised that they were included, the name is kinda incorrect now. However, you do have to zoom pretty far in to see them.

In the below screenshot I've zoomed in more than required in order to better show that they are there. The fuzzy light coloured lines are the northern edge of the ACT, the fuzzy yellow lines are the roads.

<img width="863" alt="screen shot 2017-08-01 at 20 33 35" src="https://user-images.githubusercontent.com/5283003/28821529-1be724c0-76f9-11e7-93f7-90030a79541d.png">

**Comment by juan-guerschman** [comment]
you're right @meh9 , my bad.
However it seems to me that these layers stop working at high zoom levels, is that something already set up in the source? 
example (at least here): 
http://map.geo-rapp.org/#share=s-6wiwmuCIPpJ5ZQyp9l34f0Vaj5S
and
http://map.geo-rapp.org/#share=s-aDLnCoSH3zd7r6neRxivrK54dwg
