### ISSUE TITLE
Default loading with higher zoom

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#10]
As a consequence of an issue with the low resolution tiles, the lower zoom levels don't display FC and a few other layers. A user landing at such zoom level won't have a nice experience. 

Can the default zoom level be like this one? 

http://map.geo-rapp.org/#share=s-lrRbpr7ABFwtdx9veBcwbLQcrkN

**Comment by meh9** [comment]
It is very difficult to do anything about this, because for the zoom to be high enough that you don't get any message you have to zoom in until the top and bottom of Africa is cut off on my screen.

**Comment by juan-guerschman** [comment]
ok, after talking with Pablo we decided to do the following. 
Zoom level when landing remains the same.
But default raster loaded Ttoal cover instead of Fractional Cover. 
Something like this:
http://map.geo-rapp.org/#share=s-974ncYWntg9yCGZhnkBZvlOa3Zu

This is how it looks in my screen: 
![image](https://cloud.githubusercontent.com/assets/8801702/24275403/395d70b8-1083-11e7-8b44-5dc759877731.png)

**Comment by meh9** [comment]
Have made these changes.

**Comment by juan-guerschman** [comment]
@meh9 I still see GEOGLAM RAPP loading FC by default, and not Total Cover.

**Comment by meh9** [comment]
The new version has been released.
