### ISSUE TITLE
Geoglam - v7 Jan release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#101]
Based on this ticket https://github.com/TerriaJS/devops/issues/30, this urgent release is due to expiration of Bing maps usage on 31 Jan which affects Bing maps and Bing geocoder. 
- update the Cesium ION key with premium account one
- include updated geocoder: https://github.com/TerriaJS/terriajs/issues/5107

**Comment by peterhassall** [comment]
https://map.geo-rapp.org/ has been updated with a new Bing Maps key, and configured to get imagery from Cesium ION.
