### ISSUE TITLE
v7 to v8 - dates not displayed correctly

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#104]
![image](https://user-images.githubusercontent.com/8801702/107479533-5990db80-6bcf-11eb-911f-be476081a3dd.png)
also:

![image](https://user-images.githubusercontent.com/8801702/107479708-9a88f000-6bcf-11eb-8768-ebaea5159039.png)

and

![image](https://user-images.githubusercontent.com/8801702/107479812-bd1b0900-6bcf-11eb-8c1c-0d2f63c58d0f.png)

**Comment by nf-s** [comment]
Done!

![image](https://user-images.githubusercontent.com/6187649/115681081-86175f80-a397-11eb-9b13-2e4bdeaebd45.png)
