### ISSUE TITLE
v7 to v8  -  none of the Bing Maps base layers work 

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#107]
![image](https://user-images.githubusercontent.com/8801702/107480390-9dd0ab80-6bd0-11eb-9234-d93b025c4a05.png)

**Comment by nf-s** [comment]
Fixed! Had to update bingMapsKey

**Comment by juan-guerschman** [comment]
I don't see Bing maps in https://beta.geo-rapp.terria.io/

**Comment by juan-guerschman** [comment]
looks like it's working now? Can be closed?
