### ISSUE TITLE
v7 to v8 - feature info template doesn't work as expected 

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#108]
![image](https://user-images.githubusercontent.com/8801702/107480578-ebe5af00-6bd0-11eb-94be-6d089fa3bed6.png)

https://github.com/TerriaJS/RaPPMap/blob/master/wwwroot/init/geoglam.json#L1802

(feature with template)

**Comment by juan-guerschman** [comment]
actually it does show when clicked, but not by default as we wish and like in v7

**Comment by nf-s** [comment]
Feature info is now showing by default when a feature is selected

**Comment by juan-guerschman** [comment]
I still see it collapsed by default 
https://beta.geo-rapp.terria.io/#share=s-sGT0e43vlJDDeoukZFiOIJvS9ba

**Comment by juan-guerschman** [comment]
seems to be working ok now.
