### ISSUE TITLE
legend not scaled - NDVI and Total Cover

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#11]
I see the legend as this: 
![image](https://cloud.githubusercontent.com/assets/8801702/24086154/73de46a4-0d5e-11e7-894e-4545bcbe9542.png)
not scaling to fit side column

**Comment by meh9** [comment]
Updated to resize legends to max 400px tall:

<img width="771" alt="screen shot 2017-03-20 at 11 43 15" src="https://cloud.githubusercontent.com/assets/5283003/24086373/818c9504-0d62-11e7-962f-dc27be05a108.png">
