### ISSUE TITLE
Geoglam - v8 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#115]
- [x] feature info https://github.com/TerriaJS/RaPPMap/issues/108
- [x] Bing map layers https://github.com/TerriaJS/RaPPMap/issues/107
- [x] search location - https://github.com/TerriaJS/RaPPMap/issues/106
- [x] dates display  https://github.com/TerriaJS/RaPPMap/issues/104
- [x] https://github.com/TerriaJS/RaPPMap/issues/105
- [x] https://github.com/TerriaJS/RaPPMap/issues/119

**Comment by nf-s** [comment]
Done!
