### ISSUE TITLE
Geoglam - implement multi polygon WPS

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#117]
One feature many users want is the ability to do "multiple polygons" WPS requests.
Meaning selecting several polygons, or uploading a kml/geojson with several polygons and submitting requests, and avoiding the current situation where they have to do it one by one.
Question: is something like that currrently possible with Terria? If not, how much development do you think would be associated with that?
One discussion to have also is what to do with many responses when they  come back from the backend

**Comment by na9da** [comment]
I think there are 2 aspects to implementing this requirement:

* Technical feasibility - Technically this looks feasible. The API already accepts any GeoJson `FeatureCollection` as input. So we can pass any number of Points or Polygons. The API response is a terriajs catalog definition which can have multiple catalog items, one per shape.

* UX - We need more thought on how we will change the UI to accommodate selecting multiple polygons or points. We could build a more generalized UI that allows the user to pick any number of polygons or points. We should also allow the user to remove a selected shape before submitting the job.

My time estimate will be 8 days for implementation + the time to come up with a UX design.

Also considering that @nf-s has done a lot of the WPS re-design, would like to get his thoughts as well.

**Comment by nf-s** [comment]
>We could build a more generalized UI that allows the user to pick any number of polygons or points

Yep love this idea.

This might also be a good opportunity to look into a "Drawing" or "Annotation" UI mode - maybe something similar to `leaflet-draw` works (eg http://geojson.io)
