### ISSUE TITLE
intermittent issue with Share URL

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#118]
There's an intermittent issue with Share URL's on the GEOGLAM map. Using this share URL:

https://map.geo-rapp.org/#share=s-6wRgY4AkNK1pBl8UAHhZrFLdYhT

Occasionally there is a problem loading the share URL:

<img width="903" alt="Screen Shot 2021-09-23 at 10 45 40" src="https://user-images.githubusercontent.com/5283003/134440046-19607812-5dea-4d29-9d3f-e30b117d717c.png">

The reported error when you catch it in the act is:

```
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

<img width="934" alt="Screen Shot 2021-09-23 at 10 46 55" src="https://user-images.githubusercontent.com/5283003/134440138-c7c951f7-9a13-4a3d-a488-b799d129bd09.png">

**Comment by nf-s** [comment]
No longer relevant. In Saas/v8, AWS S3 access keys are now set explicitly in TerriaJS server config
