### ISSUE TITLE
v7 to v8 - not latest version of v7 catalog in v8 beta

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#119]
example:
current v7
![image](https://user-images.githubusercontent.com/8801702/139341063-307c89e0-0376-40d8-ac77-e6ed11677911.png)

v8 beta: 
![image](https://user-images.githubusercontent.com/8801702/139341088-36b40e87-f913-4105-9311-88fc78c23ad7.png)

**Comment by nf-s** [comment]
Updated in dev

**Comment by juan-guerschman** [comment]
several urls in the beta catalog point to https://geoglam.ternlandscapes.net.au/geoserver/aust/wms when they should point to https://geoglam.ternlandscapes.org.au/geoserver/aust/wms

This was changed in Jul 22 2021: 
https://github.com/TerriaJS/RaPPMap/commit/54b6a02e15dfd6785ee0d88493b06ed49e48b92a

**Comment by nf-s** [comment]
Hi @juan-guerschman sorry I missed that change when updating the catalog.

I have added those changes to the test environment https://geo-rapp.test.saas.terria.io/

**Comment by juan-guerschman** [comment]
thanks!
