### ISSUE TITLE
Geoglam - Help pages - updates

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#120]
should be pointing to https://map.geo-rapp.org/help/help.html 

![image](https://user-images.githubusercontent.com/8801702/139781160-b21b1f8f-ae5f-47f2-b492-e78c7d8587e3.png)

**Comment by AnaBelgun** [comment]
Hi @juan-guerschman the Help feature has changed in v8 considerably. 
The help and FAQ web pages are currently decommissioned for all SaaS maps. They are very difficult to maintain individually and most of times are out of date. 

However, there are some options: 
- you add all the content you have made specifically for geoglam on a separate website and in the Help menu, we listed as a link (like we are atm with the generic user guide link): you can use any platforms or tools to write documentation. In that way, you can change it anytime, and keep it always fresh. 
- in addition to that, we could add some of that content under the Help menu; if you know there are some popular tasks with your users, you should write some step by step guides (or copy from the ones you have already), make a short video and we put them in the Help. I  think adding everything you have under Help right now, it might be too long, but we could try.

**Comment by juan-guerschman** [comment]
Ana,
I think we can go with the default mode (what I see in Nat Map and in DEA Map) , but ideally in the step by step guide add 14 points for each on e of the steps we have listed in https://map.geo-rapp.org/help/help.html 
Can we do that and switch to V8?

**Comment by AnaBelgun** [comment]
hi @juan-guerschman we need to clarify few things. 
The step by step guide is a bit different than other items in the Help menu. When you click on a topic under the Step by Step, it opens a separate workflow on the landing page. That is quite laborious to recreate for 14 different items at this stage, We're looking at re-configuring that in the future or even decommissioning. 
![image](https://user-images.githubusercontent.com/18452161/144360700-8ea68dc2-da1e-4cc1-a8e8-df279d3a4245.png)

![image](https://user-images.githubusercontent.com/18452161/144360737-ee787b15-e48e-4503-a54d-cfa61d6e31f4.png)

What I was suggesting is to have the topics under your current Help, as individual topics under the new Help menu. 

For example: 

these items 
![image](https://user-images.githubusercontent.com/18452161/144360833-b18b172d-aea9-421d-9cf9-d13f02a91636.png)

will become items under here: 
![image](https://user-images.githubusercontent.com/18452161/144360935-a15c8d45-1126-48ed-891e-cf1d3a767db5.png)

and we delete the default "getting started" and "step by step" because they are not relevant to geoglam. 
We can keep the "map user guide" which is very generic if you wish, but that can be deleted too because you have a comprehensive guide anyway. 

Let me know what you think.

**Comment by AnaBelgun** [comment]
Help links (proposed)
•	v8 Help dropdown - what to keep from:
o	gettingstarted.title > Link to Help pages (eo-data) > from Help doc
o	stepbystepguide.title > Link to Videos page (eo-data)
o	Share & Story migration > Delete
o	Map user guide > TerriaMap (generic) Help
•	About tab
o	About > Link to About page (eo-data) > Update
o	Help > Link to Help pages
o	Videos > Link to videos page
o	Privacy > Update
o	Terria Help
o	FAQ > Terria FAQ ?> keep or remove?

**Comment by AnaBelgun** [comment]
Update 31 Oct 2022: 

- [x] Redirect https://map.geo-rapp.org/about to https://eo-data.csiro.au/remotesensing/rapp-help/
- [ ] Help pop-out
a.	Change text to “We're here to help .. Find useful tips on how to use RaPP Map by either checking the guides below or by contacting the team at [geoglam.rapp at csiro.au](mailto:geoglam.rapp@csiro.au)”
b.	“Getting started” > link to https://eo-data.csiro.au/remotesensing/rapp-help/
c.	stepbystepguide.title > remove
d.	“Share & Story migration” > keep as is
e.	“Map user guide” > relabel to “TerriaJS User Guide” and keep the same link
- [x] Landing page pop up 
![image](https://user-images.githubusercontent.com/18452161/198935294-0eb50039-0b21-47aa-90cb-2ae3b8f71b8e.png)
1. Change text to: 
Geoglam RaPP Map is an online tool providing timeseries data on vegetation and environmental conditions. 
[Learn more about Geoglam RaPP Map](https://eo-data.csiro.au/remotesensing/rapp-help/)
2. Logos (keep Data61, Australian Government Coat of Arms, National Landcare and position them in centre.
3. Include Don't show this message again tickbox
4. Include Continue. 
Something like this. 
![image](https://user-images.githubusercontent.com/18452161/198935467-ed1d2657-40a0-4044-8774-f25ab99f99ee.png)

**Comment by nf-s** [comment]
PRs to add ability to change About button URL

- [x] https://github.com/TerriaJS/terriajs/pull/6611
- [x] https://github.com/TerriaJS/TerriaMap/pull/630

**Comment by nf-s** [comment]
For landing page - we don't have the ability to add "Don't show this message again" option.

I think we would need to get Phil to mockup something for this

Is this OK?

![image](https://user-images.githubusercontent.com/6187649/199425642-84a7b10c-5abb-426e-a04d-d0a0293c1fab.png)

**Comment by nf-s** [comment]
To change "help links" text, I need to add ability to override language translation files in SaaS. Should be done today

**Comment by AnaBelgun** [comment]
@nf-s instead of the checkbok can we have the same behaviour as here: 
![image](https://user-images.githubusercontent.com/18452161/199629207-705cda85-6925-4fe4-9cbc-3e4ab9e18bda.png)

i.e. we leave the disclaimer page as you did it but add at the bottom the text 
"close message and don't show me this again".

**Comment by nf-s** [comment]
We can use the "welcome message" functionality. 

At the moment we don't have a way to remove the video and buttons per map - so it will look something like this:

![image](https://user-images.githubusercontent.com/6187649/199629640-f6575844-1155-4056-a81b-4b4e289304b1.png)

We can change the video and video title easily.

**Comment by AnaBelgun** [comment]
Hm it looks a bit busy. How about we take the branding out? 

@mpaget we have a question for you; which one out of the following options would suit best? I think nr 2 is too busy, but check them out

1) No "close message and don't show me this again" but all the other elements 
![image](https://user-images.githubusercontent.com/18452161/199633617-69d274c0-121f-457b-a531-e8712f4e1ee9.png)
2) Get you started landing pop up with extra elements; we will need a new video link to replace the generic one 
![image](https://user-images.githubusercontent.com/18452161/199633718-9a4fc5e7-a3e7-4d77-96ed-1f1d09350ae2.png)
3) Get you started pop up without the logos (which users will find when they click on the Learn more...hyperlink). 
![image](https://user-images.githubusercontent.com/18452161/199633856-6c32bbd8-ddbb-458f-9312-2775e24b9d3c.png)

**Comment by mpaget** [comment]
Thanks for your work on this and considerations. I vote for option 1.
I understand the main intent of "don't show this again" is to make the entry simpler (ie.I don't want to see the previous long message again). The shorter text and logo set (option 1) reasonably meets this objective just as well, I think.

**Comment by nf-s** [comment]
PR to add ability to override translation strings per SaaS map. This is required to make specified changes to the help panel

- [x] https://github.com/TerriaJS/terriajs/pull/6615

**Comment by nf-s** [comment]
I have done the following in test - https://geo-rapp.test.saas.terria.io/

- About button now opens https://eo-data.csiro.au/remotesensing/rapp-help/
- Simplified welcome message/landing page modal
- Changes to help panel
  - Change text to “We're here to help .. Find useful tips on how to use RaPP Map by either checking the guides below or by contacting the team at [geoglam.rapp at csiro.au](mailto:geoglam.rapp@csiro.au)”
  - “Getting started” will open https://eo-data.csiro.au/remotesensing/rapp-help/
  - Removed `stepbystepguide.title`
  - Renamed "Map user guide" to “TerriaJS User Guide”

**Comment by AnaBelgun** [comment]
@mpaget hi do you have an update if we can push this to production? Thank you.

**Comment by mpaget** [comment]
Still waiting on feedback from ABARES. John said initial test looked good.

**Comment by mpaget** [comment]
Feedback received ("Looks great"). Nothing further to add at this time. Please proceed to production at your convenience. Thank you!

**Comment by AnaBelgun** [comment]
@nf-s we are ready to go (on Monday). Thank you.

**Comment by nf-s** [comment]
Pushed changes to production!

https://map.geo-rapp.org/
