### ISSUE TITLE
v7 to v8 - is 2D and initial position and zoom level easy to set up in catalog? 

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#121]
current v7 version defines that in the catalog , example https://github.com/TerriaJS/RaPPMap/blob/master/wwwroot/init/geoglam.json#L12 

also, does v8 allow for "customised initial catalog" variant?
for example, we have https://github.com/TerriaJS/RaPPMap/blob/master/wwwroot/init/australia.json  which we call with https://map.geo-rapp.org/#australia and that's very handy.
@AnaBelgun  ?

**Comment by AnaBelgun** [comment]
yes, we need to send Geoglam team an explanation

**Comment by tephenavies** [comment]
Hi @juan-guerschman. Initial camera position and setting 2d is the same in v8 as in v7. And we still support `#init-file` urls.

**Comment by AnaBelgun** [comment]
replied to question
