### ISSUE TITLE
Change zoom on landing page to focus on Australia

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#124]
Current zoom on landing page is focused on Africa 
https://geo-rapp.prod.saas.terria.io/
![image](https://user-images.githubusercontent.com/18452161/172284167-88dd8178-d59e-40a4-87cd-97f60a7473fa.png)

Change the zoom to focus on Australia
![image](https://user-images.githubusercontent.com/18452161/172284250-22fbe440-f9dd-4fd5-8797-365cf8686f3b.png)

**Comment by nf-s** [comment]
Done

https://beta.geo-rapp.terria.io/
