### ISSUE TITLE
Set Australia tab first and default

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#128]
Since this app has majority of users in Australia, make the Aus tab first and default under the Explore data tabs. 

![image](https://user-images.githubusercontent.com/18452161/185003042-a4f6487e-45ef-4968-bbf4-a77e2c012743.png)

**Comment by nf-s** [comment]
Done in 

- Dev https://geo-rapp.dev.saas.terria.io/
- Test https://geo-rapp.test.saas.terria.io/

**Comment by nf-s** [comment]
Done in production

https://map.geo-rapp.org/
