### ISSUE TITLE
Catalog reordering / additions  (under /#australia )

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#13]
[D61] Catalog reordering / additions:

- Add new heading: “Australia”. Under such heading add:
- “Land Use/Land Cover” with: 	
1. - Catchment Scale Land Use 2016: http://data.gov.au/geoserver/ws_e4c5c71b_8d42_4ff3_b062_e24a76a636c9/wms (currently in Nat Map)
2. - Land Cover: http://services.ga.gov.au/gis/rest/services/Landcover_WM/MapServer 
3. - Interim Biogeographic Regionalisation for Australia (IBRA), Version 7 (Subregions): http://www.environment.gov.au/mapping/services/ogc_services/IBRA7_Subregions/MapServer/WMSServer 
4. - Collaborative Australian Protected Areas Database (CAPAD) 2014: http://www.environment.gov.au/mapping/services/ogc_services/capad/MapServer/WMSServer 
5. - Physiographic Regions of Australia (I could not find a WMS or similar for this one) https://data.gov.au/dataset/a0f3edb6-6afd-4eb9-a9be-e815f8ec4eab 

- “Boundaries”
1. Natural Resource Management Regions: http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows?service=WMS&version=1.3.0&request=GetCapabilities
2. Local Government Areas: http://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/MapServer/7 
3. Land Tenure: http://services.ga.gov.au/gis/services/Land_Tenure_WM/MapServer/WMSServer

**Comment by meh9** [comment]
@a-stacey, this stuff goes in the file https://github.com/TerriaJS/geoglam-nm/blob/master/wwwroot/init/australia.json

**Comment by meh9** [comment]
Test like this: http://map.geo-rapp.org/#australia

**Comment by meh9** [comment]
@a-stacey, look for other init examples in: node_modules/terriajs/wwwroot/test/init/

**Comment by juan-guerschman** [comment]
Thanks guys,
A few additional requests:
Organise new layers within folders (see below and first post)
delete feral camels layer

 
- Australia 
   - Land Use/Land Cover
      1- Catchment Scale Land Use 2016: 
      2- Land Cover
      3- IBRA
      4- Collaborative Australian Protected Areas Database (CAPAD)
      5- Physiographic Regions of Australia 
   - Boundaries
      1- Natural Resource Management Regions
      2- Local Government Areas 
      3- Land Tenure

**Comment by juan-guerschman** [comment]
hi there, I have a meeting next week with the client and I was wondering if we could get this catalog reordering done as a priority in http://map.geo-rapp.org/#australia 
@a-stacey 

thanks

**Comment by a-stacey** [comment]
Hi Juan,

When is your meeting this week?

I don't work Thursday / Friday, but working on this issue this morning.

**Comment by juan-guerschman** [comment]
meeting is Thursday

**Comment by a-stacey** [comment]
Thanks.

Will let you know once these updates are in place so that you can test them to make sure there are no issues.

**Comment by juan-guerschman** [comment]
cool, great, thanks

**Comment by meh9** [comment]
@juan-guerschman, I put this live today, thanks @a-stacey!
