### ISSUE TITLE
Catalogue management - by Geoglam team 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#130]
- share catalogue JSON and instructions with Geoglam team 
- point to new catalogue file

**Comment by mpaget** [comment]
Hi,
I see that @steve9164 has updated the `README.md` to include the saas links. However, these links don't work for me - perhaps they are private repos?
We would like to be able to update the georapp catalogue, presumably via a PR, which is the intent of this issue. We're getting pretty close to needing this capability. Are you able to estimate when it may be available, please?
Cheers.

**Comment by AnaBelgun** [comment]
Hi @mpaget I've changed its priority to high to be picked up as soon as everyone is back next week.

**Comment by AnaBelgun** [comment]
Update 1 Feb 2023: 
- @steve9164 will give a copy of the catalogue file to @mpaget 
- next step is for geoglam team to create a GitHub repo with the new file and update it as they go 
- next step is to point Geoglam app to the new repository

**Comment by mpaget** [comment]
> geoglam team to create a GitHub repo with the new file and update it as they go

Yes, will do .. and will post here when the repo/file is live.

**Comment by tephenavies** [comment]
Hi @mpaget. The file to download and put into the GitHub repo is https://terria-catalogs-public.storage.googleapis.com/geo-rapp/prod.json.

If you're moving datasets around in the file, try to retain the id, and if you're adding a new dataset, it's best to generate a new random id. I recommend something like https://www.random.org/strings/?num=10&len=8&digits=on&upperalpha=on&loweralpha=on&format=html&rnd=new.

Let us know if you have any problems.

**Comment by mpaget** [comment]
Hi @steve9164, We've copied the `prod.json` to https://github.com/aus-groundcover/georapp-config/blob/main/prod.json.

No changes in the file for this first commit.

**Comment by tephenavies** [comment]
I have updated our configuration to point to your file.

**Comment by mpaget** [comment]
Hi @steve9164, It's working well. Thank you! What is the anticipated update/sync frequency or latency after a PR in our repo?

**Comment by tephenavies** [comment]
@mpaget Update time after changes are made to main should be less than 5 minutes.
