### ISSUE TITLE
Export of Total Vegetation Cover not working - investigate

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#131]
To investigate why the Total veg cover export function is not working. 
Could it be because the TVC web service is not set up to support exporting GeoTIFFs/any files? 
Comment from custodian: "it used to work in v7"

- Go to https://map.geo-rapp.org/
- remove Place Labels and Coastlines datasets from workbench 
- Under the 3 dots menu, select Export and follow the prompts to select a polygon (try to zoom in close and draw a very small polygon)
- click Download Extent
- error message
![image](https://user-images.githubusercontent.com/18452161/185512903-22cf2d3e-89c2-4667-9aa7-520fe14b84f5.png)

**Comment by nf-s** [comment]
Duplicate of https://github.com/TerriaJS/RaPPMap/issues/126
