### ISSUE TITLE
GEOGLAM RAPP instructions (for dummies)

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#14]
We wrote some "for dummies" instructions in http://www.geo-rapp.org/rapp-monitor/global-monitoring-system-rapp-map/ (beggining in "Below we give an overview of the tools available in the RAPP Map:")

Can these be merged, or referred to somehow from http://map.geo-rapp.org/about.html ?

**Comment by a-stacey** [comment]
Proposal: Add an anchor id="overview" at "HOME PAGE" in http://www.geo-rapp.org/rapp-monitor/global-monitoring-system-rapp-map/.

Further info on id attribute:
https://www.w3schools.com/html/html_links.asp

From http://map.geo-rapp.org/about.html -  "How to use the GEOGLAM RAPP Map" add a link with the following text: "A quick start guide for those new to the map is also available here: http://www.geo-rapp.org/rapp-monitor/global-monitoring-system-rapp-map/#overview ".

**Comment by mpaget** [comment]
I think this can be closed via https://github.com/TerriaJS/RaPPMap/issues/120
