### ISSUE TITLE
Terria not sending request to GSKY with some polygons - Errors 400 and 500 

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#16]
uploaded polygon to Map, tried Add Data -> Query Data -> existing polygon, selected this one and got error code 500. See print screen. 
Similar error (but code 400) when selecting same polygon from this layer: http://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/MapServer/7
Pablo Rozas says query doesn't get to GSKY 

![image](https://user-images.githubusercontent.com/8801702/26857340-49201f1c-4b6d-11e7-8381-854246cce0e7.png)

[LGAs_LGAName_BERRIGAN.zip](https://github.com/TerriaJS/geoglam-nm/files/1056623/LGAs_LGAName_BERRIGAN.zip)

**Comment by meh9** [comment]
Using the "Existing polygon" feature for the zipped KML file above is now fixed with the merging of this PR:

https://github.com/TerriaJS/terriajs-server/pull/72

(Note that the request can still time out if GSky doesn't return data in time.)

**Comment by meh9** [comment]
It appears it doesn't work with ArcGIS MapServers, only with other kind of polygons (KML, WMS). When using a MapServer based polygon layer it doesn't get a polygon name in the input box when you click the polygon. Maybe the server just isn't returning some data (like a name?) that we expect? @kring, any ideas?

**Comment by kring** [comment]
Sorry, I'm not totally following you.  Can you walk me through the problem?

**Comment by juan-guerschman** [comment]
question is for me or for @meh9 ?

**Comment by kring** [comment]
> question is for me or for @meh9 ?

@meh9, since he asked me for ideas.

**Comment by meh9** [comment]
@kring, when we use the Geoglam WPS `Query Data` catalogue item and using the `Existing Polygon` function, this works with KML files and WMS polygon layers that return geometry data, but it does not appear to work with ArcGIS MapServer layers that return polygon data. My only observation is that when using the `Existing Polygon` and clicking on a WMS polygon, a polygon name appears in the input box for the function. When doing the same with a MapServer layer of polygons no name appears and the input box is left blank.

For example, when using this ArcGIS MapServer layer, using the `Query Data` catalogue item, and the Existing Polygon function and clicking anywhere on the map, then you get nothing in the input box and so the query fails when you `Run Analysis`, even though you can click on the map for feature info and we do get the polygon data and highlight it:

http://map.geo-rapp.org/#share=s-qzoIwxBmHjQyO2NEyjDk4UraQBq

However, using this map that has a WMS polygon layer with the Existing Polygon, you do get a name of a polygon in the input field, and you can `Run Analysis`:

http://map.geo-rapp.org/#share=s-zMYNPcALgR8OoLba7Df5hpQ9Xt1

If that doesn't make sense then I'm happy doing a Skype to share my screen to discuss. :)

**Comment by kring** [comment]
That makes sense, thanks.  I'm not sure offhand why picking polygons from ArcGIS layers doesn't work though.  Will have to investigate.

**Comment by juan-guerschman** [comment]
any updates on this @meh9 @kring? I see the problem is still there. Thanks.

**Comment by meh9** [comment]
I believe that things are now working from a TerriaJS point of view with the two Pull Requests above merged.

**Comment by juan-guerschman** [comment]
I still see the same problem with this layer:
http://www.environment.gov.au/mapping/services/ogc_services/capad/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

example: http://map.geo-rapp.org/#share=s-lZ7JH8idx4EBsm5NpSL6LtesC18

same issue with this other layer: http://www.environment.gov.au/mapping/services/ogc_services/Natural_Resource_Management_Regions/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

any ideas @kring @meh9 ?

**Comment by kring** [comment]
Looks like that server isn't returning polygon geometry from GetFeatureInfo.  The response looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>

<FeatureInfoResponse xmlns:esri_wms="http://www.esri.com/wms" xmlns="http://www.esri.com/wms">
<FIELDS Shape="Polygon" Name="Nombinnie" Type="State Conservation Area" State="NSW" Environ="T" IUCN="II" AUTHORITY="NSW_OEH" GAZ_DATE="11/03/2005" PA_ID="NSW_N1028" NRS_PA="Y" GOVERNANCE="G" MGT_PLAN="P" LATEST_GAZ="11/03/2005" TYPE_ABBR="SCA" DATASOURCE="NSW_OEH" RES_NUMBER="N1028" COMMENTS="Null" X_COORD="145.774709" Y_COORD="-32.896037" Overlap="1" OBJECTID="963" GAZ_AREA="46000" GIS_AREA="46347.180591" REPT_AREA="46347.180591" SHAPE.AREA="0.044714" SHAPE.LEN="2.32519" EPBC="State"></FIELDS>
</FeatureInfoResponse>
```

That's why you also don't get a highlight when you click a polygon.  Not much we can do about that.

BUT the ArcGIS REST (instead of WMS) version of the same service _does_ include geometry.  So if you use that, it should work:
http://www.environment.gov.au/mapping/rest/services/ogc_services/capad/MapServer

**Comment by juan-guerschman** [comment]
great, @kring , how did you know about the REST thing? I mean how did you find it?

**Comment by kring** [comment]
Oh I could tell from the URL that that is an ArcGIS server, and I know how Esri structures their URLs.  Basically just remove the WMS bit of the URL and add /rest/ in the right spot.

**Comment by meh9** [comment]
I believe this is now fixed.
