### ISSUE TITLE
give default names to polygons when user draws or uploads un-named polygons

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#18]
when user draws polygons for data drills or uploads file with un-named polygons, include default names, for example polygon1, polygon2 and so on.
Will be needed later on for returning plots / data.

**Comment by meh9** [comment]
Think about giving default names to points, or let the user set it. I.e. `Point 1`, `Point 2` etc, as input fields on the WPS request, but allow users to change it.

**Comment by meh9** [comment]
The problem we're trying to solve is making several Query Data requests for say points, and knowing which response is related to which query. How do we bet connect e.g. two points on the map to their responses in the workbench/chart?

**Comment by nf-s** [comment]
I believe this is done

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6187649/177762434-0aef0e88-f4a1-420e-9579-e7884b731597.png">
