### ISSUE TITLE
change config file to show day/month/year

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#20]
can the config file (https://github.com/TerriaJS/geoglam-nm/blob/master/wwwroot/init/geoglam.json#L40) change the following: 

"currentTime": "dd mmmm yyyy",

(not sure if the syntax is correct, what I'd like is that the date is shown as "3 January 2017"

**Comment by meh9** [comment]
![image](https://user-images.githubusercontent.com/5283003/27622985-9a05306e-5c1d-11e7-9733-010d99413cb4.png)

**Comment by juan-guerschman** [comment]
thenks @meh9 , I forgot to attach that for clarity

**Comment by a-stacey** [comment]
Looks like there are 8 layers with the same formatting, do you want it changed for all:
- Vegetation Fractional Cover (PV, NPV & BS)
- Normalised Difference Vegetation Index (NDVI)
- Total Vegetation Cover (PV + NPV)
- Total Vegetation Cover Anomaly
- Rainfall-CHIRPS Precipitation - Absolute
- Rainfall-Anomalies
- Soil Moisture-Absolute
- Soil Moisture-Anomalies

**Comment by juan-guerschman** [comment]
oh, I didn't realise it's layer-dependent.
I'd say it's for the following three (8-day step data): 

- Vegetation Fractional Cover (PV, NPV & BS)
- Normalised Difference Vegetation Index (NDVI)
- Total Vegetation Cover (PV + NPV)

**Comment by a-stacey** [comment]
Have updated for those 3 layers.

I don't understand the context of "8-day step data"?

**Comment by juan-guerschman** [comment]
Thanks. I guess I have to wait until a refresh to see the changes? 
"8-day step data" means that those 3 layers have an image every 8 days, not every month.

**Comment by a-stacey** [comment]
Ah sure.

Yep will have to wait for a refresh to see the changes (not sure what the effort or constraints are around setting up continuous deployment).
