### ISSUE TITLE
Make the Query Data input show warning for no data

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#22]
The Query Data input field should show when it doesn't have any data, so the user will know if the query is going to work or not.

**Comment by a-stacey** [comment]
I have added the following warning below the location text.

![locationwarning](https://user-images.githubusercontent.com/4453477/28004452-20178440-6588-11e7-924b-e83f0a94c140.png)

I looked into disabling the Run Analysis button when the warning is present, but it doesn't seem to be trivial to modify to support this behavior.
