### ISSUE TITLE
WPS response Data URL in About This Dataset is missing the hostname

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#3]
When you run a WPS process and get a response, the About This Dataset catalogue entry that is generated has a Data URL:

<img width="618" alt="screen shot 2017-02-01 at 09 15 52" src="https://cloud.githubusercontent.com/assets/5283003/22486795/15cd381e-e85f-11e6-9825-160e961f9205.png">

This Data URL returns a 404 because it's missing the hostname of the WPS server.

We should investigate why it's missing the hostname and fix it or log a TerriaJS issue if necessary.

To reproduce:

1. Go to http://map.geo-rapp.org/#test
2. Add Data -> Test Data -> WPS National Map Tests -> Json Output
3. Chose a point and run the test
4. Click the About This Dataset on the Json Output catalogue entry in the workbench.
5. Scroll down to Data URL.

**Comment by nahidakbar** [comment]
Done and tested. PR #2362

**Comment by meh9** [comment]
This has been fixed.
