### ISSUE TITLE
"area borders" and "area labels" fail to display at high zoom levels

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#46]
works:
https://map.geo-rapp.org/#share=s-7bJLELvjmNUA3pme7MEJ63UvyQx

doesn't work: 
https://map.geo-rapp.org/#share=s-kIBCHhfKW3n4x3uKkbsUbHUREIo

![image](https://user-images.githubusercontent.com/8801702/37438445-878c68a8-2846-11e8-8a12-22c939be0324.png)

![image](https://user-images.githubusercontent.com/8801702/37438451-91f2d9ee-2846-11e8-9a7b-bd6fd5ea54ff.png)

**Comment by juan-guerschman** [comment]
was answered by @kring in here https://github.com/TerriaJS/terriajs/issues/2930#issuecomment-378796522

**Comment by meh9** [comment]
Actually not fixed, this is a different error.

**Comment by juan-guerschman** [comment]
can I bring this issue to the main TerriaJS GitHub to give it more visibility or it would be cheating? @meh9

**Comment by juan-guerschman** [comment]
Actually @kring suggested a fix, in https://github.com/TerriaJS/terriajs/issues/2930#issuecomment-378796522 : 

"
It's in `devserverconfig.json`. I'm not sure if that's something you maintain in GEOGLAM or not. But @meh9 or whoever should be able to add it in any case.
"

Can you give me a hand in finding where to do that?

**Comment by meh9** [comment]
The suggested fix in #2930 is for a different error and doesn't help here - it's for when we get unknown errors, i.e. no HTTP status code. The problem here is that we get a HTTPS status code 400, which is not unknown.

Adding the GIBS server to the proxy whitelist isn't going to fix this.

This issue is already logged in TerriaJS as #2945. The reason it's not been looked at is that this is the only example we have of this issue. I'll try to prioritise it higher.

**Comment by juan-guerschman** [comment]
ah, ok. It's not priority, but an annoying error. 
Brought it here as I thought the fix was easy. 
thanks

**Comment by soyarsauce** [comment]
Hi @AnaBelgun - this looks resolved with the latest update in the https://github.com/TerriaJS/geoglam-nm/issues/60 release, I don't have sufficient permissions to close issues on this repo

**Comment by meh9** [comment]
@soyarsauce I think I've given you perms now, try again?

**Comment by juan-guerschman** [comment]
great stuff, thanks. I leave those two layers open by default and no error message now when zooming in.

**Comment by soyarsauce** [comment]
Yep thanks @meh9 !
