### ISSUE TITLE
Investigate TerriaJS CSV default enabled column in graph off-by-one

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#5]
When a CSV with multiple columns is added to a graph one column is enabled by default. For some reason it is not the first column but the second one. Investigate if this is a Geoglam or Terria problem and fix/log issue as appropriate.

To test in Geoglam, load #test init file and run Test Data -> WPS National Map Tests -> Json Output, on any point. The result looks like:

<img width="339" alt="screen shot 2017-02-03 at 09 24 55" src="https://cloud.githubusercontent.com/assets/5283003/22571228/f97ee870-e9f2-11e6-90a3-46ebbaf4e250.png">

Note how NPV is the default enabled column instead of PV.

**Comment by a-stacey** [comment]
Enable of column is made on https://github.com/TerriaJS/terriajs/blob/master/lib/Models/TableCatalogItem.js#L754

**Comment by a-stacey** [comment]
Have submitted a PR for this:
https://github.com/TerriaJS/terriajs/pull/2587
