### ISSUE TITLE
Investigate why chart does not respect "yAxisMax" values

### ISSUE THREAD

**Issue by meh9** [TerriaJS/geoglam-nm#6]
Loading the `#test` init file and using the Test Data -> WPS from GSky-dev -> Geometry Drill on this point: -18.8335153964335,135.5764389038086 (use the search field to go there)

PV/NPV/BS `yAxisMax` are all set to 100, but the graph shows values up over 200:

<img width="1440" alt="screen shot 2017-02-07 at 18 28 58" src="https://cloud.githubusercontent.com/assets/5283003/22681811/568ce184-ed63-11e6-8c0e-2b545c48d022.png">

Investigate and log a bug if necessary.

**Comment by nahidakbar** [comment]
Done but could not be tested. Reproduction steps does not seem to work in my box. PR #2362

**Comment by meh9** [comment]
Now respects the yAxisMax.
