### ISSUE TITLE
Geoglam - Apr 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#60]
checklist for Apr: 

- [ ] update with latest terriajs version if possible with: https://github.com/TerriaJS/terriajs/issues/3285 and the story: https://github.com/TerriaJS/terriajs/pull/3228 and https://github.com/TerriaJS/terriajs/pull/3257

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/geoglam-nm/issues/46 will also be resolved (via https://github.com/TerriaJS/terriajs/pull/3289) once geoglam is updated with the latest terriajs

**Comment by juan-guerschman** [comment]
https://github.com/TerriaJS/geoglam-nm/issues/46  !!  awesome, that feature is something we really like.

**Comment by AnaBelgun** [comment]
update done
