### ISSUE TITLE
Investigate & spec: Implement a custom catalog function for vegcover.com

### ISSUE THREAD

**Issue by na9da** [TerriaJS/geoglam-nm#63]
`vegcover.com` API returns a custom response which cannot be handled by the existing `WebProcessingCatalogFunction`. Implement a custom interface for `vegcover.com`.

Following is a successful API request:

`curl 'https://vegcover.com/tsjson' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://vegmachine.net/' -H 'Origin: https://vegmachine.net' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'geoJsonPoly=%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%22VMId%22%3A%22Polygon1%22%2C%22selected%22%3Atrue%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B144.940567%2C-26.949005%5D%2C%5B144.937477%2C-27.08939%5D%2C%5B145.079613%2C-27.092447%5D%2C%5B145.06897%2C-26.947169%5D%2C%5B144.940567%2C-26.949005%5D%5D%5D%7D%7D%5D%7D&wmsLayer=aus%3Afractional_cover&monthlyRainfall=yes' --compressed`

**Comment by AnaBelgun** [comment]
pending product owner decision

**Comment by AnaBelgun** [comment]
to park for now
