### ISSUE TITLE
Link NRMs guide from About pages

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#67]
NRMs representatives find it sometimes very difficult to navigate the tool. 
This guide document should be linked from somewhere in the About pages: https://drive.google.com/file/d/17q0G9jfdHtfQKrL_3qo0aC4XKWvf4ogb/view

**Comment by juan-guerschman** [comment]
I am just getting up to speed with all the things happening, but one of our priorities is to completely revamp the help / about section of GEOGLAM.

**Comment by mpaget** [comment]
I think this can be closed via https://github.com/TerriaJS/RaPPMap/issues/120
