### ISSUE TITLE
Update logos 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#77]
- to update TERN logo on About pages 
- logo here: https://drive.google.com/file/d/1HMGP6NX9ZEedNHLs4eAecV1wY5ZBAsKc/view

**Comment by na9da** [comment]
I have already replaced the logo with one @Bis-Bala sent me over email, it has TERN + NCRIS in one image that you can [see here](https://github.com/TerriaJS/geoglam-nm/blob/master/wwwroot/images/tern.png).
