### ISSUE TITLE
can the name of the repository be changed?

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/geoglam-nm#84]
from "geoglam" to something else? 
Or it messes up lots of other things downstream?

**Comment by AnaBelgun** [comment]
hi @juan-guerschman what is the new name?

**Comment by juan-guerschman** [comment]
what about RaPPMap ?

**Comment by AnaBelgun** [comment]
Hi @KeyboardSounds when you do the release, would you mind changing the repo name and see if we break anything? I would but not sure if causing any issues.

**Comment by KeyboardSounds** [comment]
>Hi @KeyboardSounds when you do the release, would you mind changing the repo name and see if we break anything? I would but not sure if causing any issues.

@AnaBelgun I don't have the right permissions on the repo to do that, I'm afraid. You'll have to do it for me. No need to wait for a release, just do it and then let me know

**Comment by meh9** [comment]
Fixed!

https://github.com/TerriaJS/RaPPMap
