### ISSUE TITLE
Catalog-Converter notes

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/geoglam-nm#92]
#### Models required
- esri-mapServer
- ckan-resource
- wps

#### Properties missing
- ignoreUnknownTileErrors (underway)
- preserveOrder  (underway)
- featureInfoTemplate.info
- featureInfoTemplate.formats (underway)
- keepOnTop (underway)
- clipToRectangle (underway)
- useOwnClock (deprecated)

**Comment by nf-s** [comment]
Some of those properties are covered by https://github.com/TerriaJS/catalog-converter/issues/12

**Comment by na9da** [comment]
[WPS](https://github.com/TerriaJS/terriajs/blob/next/lib/Models/WebProcessingServiceCatalogFunction.ts#L98) exists right? Or is it not complete enough to suppor the geoglam service?

**Comment by rowanwins** [comment]
Yep WPS is implemented in next, 🤞 enough for geoglam configuations

**Comment by nf-s** [comment]
## Errors as of 07/07/2022

```sh
Error stats:
{
  "unknownProps": 0,
  "missingRequiredProps": 0,
  "unknownTypes": 0,
  "inputNotPlainObjects": 0
}
Warning stats:
{
  "unknownProps": 50,
  "missingRequiredProps": 0,
  "unknownTypes": 0,
  "inputNotPlainObjects": 0
}
Unknown types: {}
Unknown properties: {
  "WebMapServiceCatalogItem": {
    "useOwnClock": 18,
    "": 1
  },
  "EsriMapServerCatalogItem": {
    "layer name": 3,
    "ignoreUnknownTileErrors": 22
  },
  "CkanCatalogItem": {
    "debugFormat": 2
  },
  "GeoJsonCatalogItem": {
    "preserveOrder": 2,
    "featureInfoTemplate.info": 2
  }
}
```
