### ISSUE TITLE
User alerts - investigate options 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#93]
The Geoglam team would like to create alerts on the landing page depending on the reason. Ideally they would like to edit the page themselves. 
Here is an example: 
_NCI is alerting about "Periodic 10min downtimes 9am-5pm 21-22 October 2020" which affects RaPP Map (GSKY, the MODIS layers and analysis tools)._

**Comment by juan-guerschman** [comment]
I have a ticket about this already: 
https://github.com/TerriaJS/terriajs/issues/3685

**Comment by soyarsauce** [comment]
@na9da added this via https://github.com/TerriaJS/RaPPMap/pull/79 a while back, 

@na9da to review and generalise for terriajs / v8

**Comment by soyarsauce** [comment]
Next sprint as @AnaBelgun flagged this to be addressed post-rollout

**Comment by soyarsauce** [comment]
Investigate this sprint

**Comment by AnaBelgun** [comment]
Implementation similar to disclaimer (through the configuration)

**Comment by na9da** [comment]
For the new instance, I have configured a downtime notice in the disclaimer config that can be turned on/off using a bit of CSS. That should do the job for now!

**Comment by juan-guerschman** [comment]
is this ready to be tested? How does it work?

**Comment by AnaBelgun** [comment]
to park for now
